#!/usr/bin/env bash
# Post-build hook: extract the SRI integrity attributes Trunk already wrote
# into dist/index.html and emit a flat `HASHES.txt`.
#
# Format, one line per asset:
#     <integrity-hash>  <filename>
#
# This file is the canonical "what's in the deployed build" manifest.
# Ship it alongside each release (commit to the repo or upload to GitHub
# Releases) so users / auditors can compare:
#   1. the hashes their browser actually loaded (visible in <IntegrityCheck/>)
#   2. the hashes advertised in this file
#   3. the hashes produced by rebuilding from the tagged source
#
# All three matching = the browser is running the same code as the repo.
set -euo pipefail

# Trunk sets this to the staged dist dir. Fall back to repo-relative for
# manual runs.
STAGING="${TRUNK_STAGING_DIR:-$(dirname "$0")/../dist}"
INDEX="$STAGING/index.html"
OUT="$STAGING/HASHES.txt"

if [[ ! -f "$INDEX" ]]; then
    echo "emit-hashes.sh: $INDEX not found — skipping" >&2
    exit 0
fi

{
    echo "# IdeaForge deployed asset hashes (sha384 / SRI)"
    echo "# Format: <integrity>  <filename>"
    echo "# Generated by trunk post_build hook from index.html."
    echo "# Verify a deployed build by fetching this file + comparing to"
    echo "# a fresh \`trunk build\` on the tagged source."
    echo "# Generated at: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
    echo ""
    # Find every HTML tag with both href/src AND an integrity= attribute.
    # `|| true` keeps grep's no-match exit from tripping pipefail on tags
    # that don't carry an integrity hash.
    grep -oE '<(link|script)[^>]+>' "$INDEX" | while IFS= read -r tag; do
        integ=$(printf '%s' "$tag" | { grep -oE 'integrity="[^"]+"' || true; } | head -n1 | sed -E 's/integrity="(.*)"/\1/')
        if [[ -z "$integ" ]]; then continue; fi
        href=$(printf '%s' "$tag" | { grep -oE '(href|src)="[^"]+"' || true; } | head -n1 | sed -E 's/(href|src)="(.*)"/\2/')
        if [[ -z "$href" ]]; then continue; fi
        href="${href#/}"
        printf '%s  %s\n' "$integ" "$href"
    done | sort -u
} > "$OUT"

echo "emit-hashes.sh: wrote $OUT"
