//! SeaORM entity definitions.
//!
//! These will be generated by `sea-orm-cli generate entity` once the
//! database migrations are applied. For now, they serve as module stubs
//! documenting the expected entity structure.

pub mod user;
pub mod idea;
pub mod approval;
pub mod contribution;
pub mod pledge;
pub mod todo;
pub mod category;
pub mod expert_application;
pub mod notification;
